#[[header]]
#   identifier = "stake"
#    name = "Stake"
#    url = "https://staking.atom.one/"
#    weight = 1
#    params = { "variant" = "Outlined"}

#[[header]]
#    identifier = "govern"
#    name = "Govern"
#    url = "https://gov.atom.one/"
#    weight = 2
#    params = { "variant" = "Light"}

#[[header]]
#    identifier = "github"
#    name = "FORK ME ON GITHUB"
#    url = "https://github.com/atomone-hub"
#    weight = 1

[[header]]
   identifier = "telegram"
    name = "JOIN OUR TELEGRAM"
    url = "https://t.me/youwillatone"
    weight = 2
    [header.params]
        pixelURL = "https://arttrk.com/pixel/?ad_log=referer&action=registration&pixid=a4020bac-f28c-4281-b86e-ad4dfc9590c1"
        pixelOn = "click"
        analyticsTag = "plausible-event-name=Click+CTA+Telegram plausible-event-position=HeaderMenuFlag"


[[resource]]
    identifier = "ecosystem"
    name = "Ecosystem"
    url = "/ecosystem/"
    weight = 1

[[resource]]
    identifier = "faq"
    name = "FAQ"
    url = "/faq/"
    weight = 2

[[resource]]
    identifier = "roadmap"
    name = "Roadmap"
    url = "/roadmap/"
    weight = 3

[[resource]]
    identifier = "run-node"
    name = "Run Node"
    url = "/run-node/"
    weight = 4

[[resource]]
    identifier = "submit-tx-securely"
    name = "Submit TX Securely"
    url = "/submit-tx-securely/"
    weight = 5

[[resource]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 6

[[resource]]
    identifier = "docs"
    name = "Docs"
    url = "https://docs.atom.one"
    weight = 7
    analyticsTag = "plausible-event-name=Click+Header+Github plausible-event-position=HeaderMenu"

[[general]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[general]]
    identifier = "ecosystem"
    name = "Ecosystem"
    url = "/ecosystem/"
    weight = 2

[[general]]
    identifier = "faq"
    name = "FAQ"
    url = "/faq/"
    weight = 3

[[general]]
    identifier = "privacy"
    name = "Privacy Policy"
    url = "/privacy/"
    weight = 4

[[general]]
    identifier = "terms"
    name = "Terms and Conditions"
    url = "/terms/"
    weight = 5

[[general]]
    identifier = "branding"
    name = "Brand Assets"
    url = "https://github.com/atomone-hub/assets/tree/main/logos"
    weight = 6
    [general.params]
        analyticsTag = "plausible-event-name=Click+Footer+Branding plausible-event-position=FooterMenu"

[[advanced]]
    identifier = "run-node"
    name = "Run Node"
    url = "/run-node/"
    weight = 1

[[advanced]]
    identifier = "roadmap"
    name = "Roadmap"
    url = "/roadmap/"
    weight = 2

[[advanced]]
    identifier = "submit-tx-security"
    name = "Submit TX Securily"
    url = "/submit-tx-securely/"
    weight = 3

[[apps]]
    identifier = "govdapp"
    name = "AtomOne Governance dApp"
    url = "https://gov.atom.one/"
    weight = 1
    [apps.params]
        analyticsTag = "plausible-event-name=Click+CTA+GovDapp"

[[apps]]
    identifier = "stakingdapp"
    name = "AtomOne Staking dApp"
    url = "https://staking.atom.one/"
    weight = 2
    [apps.params]
        analyticsTag = "plausible-event-name=Click+CTA+StackingDapp"

[[social]]
    identifier = "/atomone-hub"
    name = "github"
    url = "https://github.com/atomone-hub"
    weight = 4
    [social.params]
        label = "Github"
        listed = true
        analyticsTag = "plausible-event-name=Click+CTA+Github"

[[social]]
    identifier = "/atomone"
    name = "discord"
    url = "https://discord.com/invite/atomone"
    weight = 3
    [social.params]
        label = "Discord Community"
        listed = true
        analyticsTag = "plausible-event-name=Click+CTA+Discord"

[[social]]
    identifier = "/_atomone"
    name = "x"
    url = "https://x.com/_atomone"
    weight = 2
    [social.params]
        label = "X (Twitter)"
        listed = true
        analyticsTag = "plausible-event-name=Click+CTA+Twitter"

[[social]]
    identifier = "Telegram community"
    name = "telegram"
    url = "https://t.me/youwillatone"
    weight = 1
    [social.params]
        label = "Telegram"
        listed = true
        analyticsTag = "plausible-event-name=Click+CTA+Telegram"


[[social]]
    identifier = "AtomOne&nbsp;Forum"
    name = "forum"
    url = "https://common.xyz/atomone/"
    weight = 5
    [social.params]
        label = "AtomOne Forum"
        listed = true
        analyticsTag = "plausible-event-name=Click+CTA+Forum"


[[social]]
    identifier = "r/atomone"
    name = "reddit"
    url = "https://www.reddit.com/r/atomone/"
    weight = 6
    [social.params]
        label = "Reddit Community"
        listed = true
        analyticsTag = "plausible-event-name=Click+CTA+Reddit"


[[social]]
    identifier = "AtomOneHub"
    name = "youtube"
    url = "https://www.youtube.com/@AtomOneHub"
    weight = 7
    [social.params]
        label = "Youtube"
        listed = true
        analyticsTag = "plausible-event-name=Click+CTA+Youtube"

